name: CI Pipeline

on: 
  push:
    branches: [main, dev-branch]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
    
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
    
      - name: Test with pytest
        env: 
          X_ADMIN_TOKEN: ${{secrets.X_ADMIN_TOKEN}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: pytest


